spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8005

mybatis-plus:
  #config-location: classpath:mybatis/mybatis.cfg.xml       # mybatis配置文件所在路径
  type-aliases-package: com.liu.entity                 # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
   name: springcloud-dept						#微服务最重要的是取名字！微服务对外暴露的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/bj1903            # 数据库名称
    username: root
    password: 19981010
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
      instance-id: springcloud-dept:8005        #修改别名
      prefer-ip-address: true        #显示IP地址
info:
  app.name:  springcloud-dept
  company.name:  www.liu.com
  build.artifactId:  $project.artifactId$
  build.version:  $project.version$

---
server:
  port: 8005

mybatis-plus:
  #config-location: classpath:mybatis/mybatis.cfg.xml       # mybatis配置文件所在路径
  type-aliases-package: com.liu.entity                 # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
   name: springcloud-dept						#微服务最重要的是取名字！微服务对外暴露的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/bj1903            # 数据库名称
    username: root
    password: 19981010
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
      instance-id: springcloud-dept:8005        #修改别名
      prefer-ip-address: true        #显示IP地址
info:
  app.name:  springcloud-dept
  company.name:  www.liu.com
  build.artifactId:  $project.artifactId$
  build.version:  $project.version$
